security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

#spring: # <---NEW SECTION, default is route
#  cloud:
#    services:
#      registrationMethod: direct

